stages:
  - deploy

deploy:
  stage: deploy
  script:
    - cd /var/www/dockerizer-service
    - git pull server master
    - docker build -t localhost:5000/xerac/dockerizer --force-rm --build-arg PRODUCTION=1 .
    - docker push localhost:5000/xerac/dockerizer
    - kubectl rollout restart deployment/dockerizer-deployment
