stages:
  - deploy

deploy:
  stage: deploy
  script:
    - docker build -t registry.syfract.com/roboepics/packman --build-arg PRODUCTION=1 .
    - docker push registry.syfract.com/roboepics/packman
    - kubectl --kubeconfig=$HOME/.kube/config-dknext rollout restart deployment/roboepics-packman
