stages:
  - deploy

deploy:
  stage: deploy
  script:
    - docker build -t registry.syfract.com/roboepics/packman --force-rm --build-arg PRODUCTION=1 .
    - docker push registry.syfract.com/roboepics/packman
    - kubectl rollout restart deployment/roboepics-packman
